- name: Start
  hosts: ipfs
  become: true
  tasks:
    - name: Start services
      ansible.builtin.systemd:
        name: "{{ item }}"
        state: started
      ignore_errors: true
      with_items:
        - ipfs
        - ipfs-cluster
