- hosts: ipfs
  become: yes
  tasks:
    - name: stop ipfs service
      ansible.builtin.systemd:
        name: ipfs
        state: stopped
      ignore_errors: true
    - name: stop ipfs-cluster service
      ansible.builtin.systemd:
        name: ipfs-cluster
        state: stopped
      ignore_errors: true
