- name: Update-ipfs-cluster-service
  hosts: ipfs
  become: true
  tasks:
    - name: Make local IPFS Cluster(EC) executable
      when: not ansible_check_mode
      ansible.builtin.shell: cd {{ ipfs_cluster_project_path }}/cmd/ipfs-cluster-service && make
      delegate_to: localhost
      changed_when: true

    - name: Copy IPFS Cluster from local to remote
      when: not ansible_check_mode
      become: true
      ansible.builtin.copy:
        src: "{{ ipfs_cluster_project_path }}/cmd/ipfs-cluster-service/ipfs-cluster-service"
        dest: "/usr/local/bin/ipfs-cluster-service"
        owner: root
        group: root
        mode: "0755"

    - name: Restart services
      ansible.builtin.systemd:
        name: "ipfs-cluster"
        state: restarted
      ignore_errors: true
