- name: Make local IPFS Cluster(EC) executable
  when: not ansible_check_mode
  shell: cd {{ ipfs_cluster_project_path }}/cmd/{{ item }} && make
  delegate_to: localhost
  with_items:
    - ipfs-cluster-service
    - ipfs-cluster-ctl

- name: Copy IPFS Cluster from local to remote
  when: not ansible_check_mode
  become: true
  copy:
    src: "{{ ipfs_cluster_project_path }}/cmd/{{ item }}/{{ item }}"
    dest: "/usr/local/bin/{{ item }}"
    owner: root
    group: root
    mode: "0755"
  with_items:
    - ipfs-cluster-service
    - ipfs-cluster-ctl

- name: Install ipfs-cluster init service
  become: true
  template:
    src: etc/systemd/system/ipfs-cluster.service
    dest: /etc/systemd/system/ipfs-cluster.service
    owner: root
    group: root
    mode: 0644
  notify:
    - Reload systemd
  when:
    - not (ansible_distribution == "Amazon" and ansible_distribution_major_version == "NA")
    - not (ansible_distribution == "Ubuntu" and ansible_distribution_version is version('15.04', '<'))
    - not (ansible_distribution == "Debian" and ansible_distribution_version is version('8', '<'))

- name: Install ipfs-custer init service
  become: true
  template:
    src: etc/init.d/ipfs-cluster
    dest: /etc/init.d/ipfs-cluster
    owner: root
    group: root
    mode: 0744
  notify:
    - Restart IPFS Cluster
  when:
    - (ansible_distribution == "Amazon" and ansible_distribution_major_version == "NA") or
      (ansible_distribution == "Ubuntu" and ansible_distribution_version is version('15.04', '<')) or
      (ansible_distribution == "Debian" and ansible_distribution_version is version('8', '<'))

- name: Make .ipfs-cluster directory
  become: true
  file:
    state: directory
    mode: 0700
    owner: ipfs
    group: ipfs
    dest: "{{ ipfs_home }}/.ipfs-cluster"
  tags:
    - clean and restart

- name: Copy configuration
  become: true
  template:
    src: "{{ item }}"
    dest: "{{ ipfs_home }}/.ipfs-cluster/{{ item }}"
    mode: 0600
    owner: ipfs
    group: ipfs
  tags:
    - clean and restart
  with_items:
    - identity.json
    - service.json
  notify: Restart IPFS Cluster

- name: set version file (to notify restart on upgrades)
  become: true
  copy:
    content: "{{ ipfs_cluster_version }}"
    dest: "{{ ipfs_home }}/cluster_deployed_version"
    mode: 0644
    owner: ipfs
    group: ipfs
  notify: Restart IPFS Cluster

- name: Copy peerstore
  become: true
  template:
    src: peerstore
    dest: "{{ ipfs_home }}/.ipfs-cluster/peerstore"
    mode: 0600
    owner: ipfs
    group: ipfs
    force: false # do not overwrite
  notify: Restart IPFS Cluster
  tags:
    - clean and restart
